name: PostgreSQL
on: push
jobs:
  postgres:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Query database
        run: psql -d postgres_db -U postgres_user -c 'SELECT 1;'
        env:
          PGHOST: localhost
          PGUSER: postgres_user
          PGPASSWORD: postgres_password
